---
title: "6-Analyze_Network"
author: "Cathy Magnée"
date: "2024-07-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Analyze networks

This documents is the sixth in this project. The first goal is to make the network files Cytoscape-ready. The first things to tackle are issues in uniformity and duplicates.

#### Loading

```{r}
library(readr)
library(dplyr)
```
Loop:
```{r, include=FALSE}
# T48_input_path <- "../ourdata/cosmos/T48_cosmos_inputs.RData" # Laptop only
T48_input_path <- "L:\\basic\\divg\\EXIM\\ImmunoHematology\\Cathy Magnée\\Data\\CD3_HDvsCLL\\CosmosR\\T48_cosmos_inputs.RData"
T0_input_path <- "L:\\basic\\divg\\EXIM\\ImmunoHematology\\Cathy Magnée\\Data\\CD3_HDvsCLL\\CosmosR\\T0_cosmos_inputs.RData"

load(T0_input_path)
load(T48_input_path)

# T48_cosmos_inputs <- day2_cosmos_inputs #Laptop only

# edit these based on variables just to create network
cosmos_inputs <- T0_cosmos_inputs 
max_depth <- 4
stim_point <- "T0"
filter <- "125" 

# Path to where the data should be:

core_path <- "L:/basic/divg/EXIM/ImmunoHematology/Cathy Magnée/Data/CD3_HDvsCLL/CosmosR"

result_path <- paste("/Networks/d", max_depth, sep = "") # Add depth folder
result_path <- paste(result_path, paste("/f", filter, sep = ""), sep = "") # Add filter folder
result_path <- paste(result_path, paste("/", stim_point, sep = ""), sep = "") # Add stim/unstim point folder
result_path <- paste(result_path, "/csvs/", sep = "") # Add csv folder

data_path <- paste(core_path, result_path, sep = "")

# Path to where result will be saved to:

# SIF_path <- paste("../results/d", paste(max_depth, paste(patient, "_SIF_full.csv", sep = ""), sep = ""), sep = "")
# ATT_path <- paste("../results/d", paste(max_depth, paste(patient, "_ATT_full.csv",sep = ""), sep = ""), sep = "")


# SIF_path <- paste("../results/Networks/d7_filter11_h4_T48/d", paste(max_depth, paste(patient, "_SIF_full.csv", sep = ""), sep = ""), sep = "")
# ATT_path <- paste("../results/Networks/d7_filter11_h4_T48/d", paste(max_depth, paste(patient, "_ATT_full.csv",sep = ""), sep = ""), sep = "")


# SIF <- read_csv(SIF_path)
# ATT <- read_csv(ATT_path)


# Edit below to what you want to preprocess

for (patient in names(cosmos_inputs)){
  # insert paths
  SIF_path <- paste(data_path, paste(patient, "_SIF_full.csv", sep = ""), sep = "")
  SIF <- read_csv(SIF_path)

  ATT_path <- paste(data_path, paste(patient, "_ATT_full.csv",sep = ""), sep = "")
  ATT <- read_csv(ATT_path)
  
  SIF$Node1 <- sub(".*__", "", SIF$Node1)
  SIF$Node2 <- sub(".*__", "", SIF$Node2)
  ATT$Nodes<- sub(".*__", "", ATT$Nodes)
  
  SIF$Node1 <- sub(',', "", SIF$Node1)
  SIF$Node2 <- sub(',', "", SIF$Node2)
  ATT$Nodes<- sub(',', "", ATT$Nodes)
  SIF$Node1 <- sub(',', "", SIF$Node1)
  SIF$Node2 <- sub(',', "", SIF$Node2)
  ATT$Nodes<- sub(',', "", ATT$Nodes)
  
  SIF <- SIF |>
  filter(Node1 != Node2) |> # First removing nodes that are re-activating themselves
  group_by(Node1, Sign, Node2) |>
  summarize(Weight = sum(Weight), .groups='drop')
  
  # Remove _c and _m from Node names (metabolites). But write down in NodeType # Cancelled because it gives information about cell system.
  # ATT$NodeType <- ifelse(grepl("_c$", ATT$Nodes) & is.na(ATT$NodeType), "C", ATT$NodeType)
  # ATT$NodeType <- ifelse(grepl("_m$", ATT$Nodes), "M", ATT$NodeType)
  # 
  # SIF$Node1 <- sub("_m", "", SIF$Node1)
  # SIF$Node2 <- sub("_m", "", SIF$Node2)
  # ATT$Nodes<- sub("_m", "", ATT$Nodes)
  # 
  # SIF$Node1 <- sub("_c", "", SIF$Node1)
  # SIF$Node2 <- sub("_c", "", SIF$Node2)
  # ATT$Nodes<- sub("_c", "", ATT$Nodes)
  
  # Add additional column "Acticity_ (patient network name)". This will make network processing within cytoscape easier.
  temp <- paste("Activity_", patient, "")
  ATT[temp] <- ATT$Activity

  # Add additional column "In_(patient network name)". This will make network processing within cytoscape easier.
  temp <- paste("In_", patient,sep = "")
  ATT[temp] <- 1
 
  # Saving processed csvs
  write_csv(SIF, file = paste(data_path, paste(patient, "_SIF_processed.csv", sep = ""), sep = ""))
  write_csv(ATT, file = paste(data_path, paste(patient, "_ATT_processed.csv", sep = ""), sep = ""))
  
}


# networks.path <- "../results/"
# all_files <- list.files(path = networks.path, pattern = "*._full.csv", full.names = TRUE)


```

