---
title: "7 - Postprocessing network results"
author: "Cathy Magnée"
date: "2024-07-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Analyzing network results

Document for analyzing the overlapping notes in the networkz. Messiest out there. You're welcome. Good luck. 


## Loading...

```{r}
library(readr)
library(dplyr)
```

Path AMC
```{r}

T0_input_path <- "L:\\basic\\divg\\EXIM\\ImmunoHematology\\Cathy Magnée\\Data\\CD3_HDvsCLL\\CosmosR\\T0_cosmos_inputs.RData"
T48_input_path <- "L:\\basic\\divg\\EXIM\\ImmunoHematology\\Cathy Magnée\\Data\\CD3_HDvsCLL\\CosmosR\\T48_cosmos_inputs.RData"

```

Path Laptop
```{r}
# T0_input_path <- "../ourdata/cosmos/T0_cosmos_inputs.RData"
# T48_input_path <- "../ourdata/cosmos/T48_cosmos_inputs.RData"

```

Loop to get paths of patient ATTs
```{r}
load(T0_input_path)
load(T48_input_path)


max_depth <- 2
# T48_cosmos_inputs <- day2_cosmos_inputs # Laptop ONLY
cosmos_inputs <- T0_cosmos_inputs # edit these as please you
stim_point <- "T0"

# path for most data files in this project
data_path <- paste("../results/processed_results/d", paste(max_depth, paste("/", paste(stim_point, "/", sep = ""), sep = ""), sep = ""), sep = "")
# file for either CLL or HD overlap nodes
overlap_path <- paste(data_path, "CLL_overlap_nodes.txt", sep = "")

# Edit below to what you want to preprocess
CLL_overlap_activities <- as.data.frame(read_delim(overlap_path, delim = "/n", col_names = FALSE))
colnames(CLL_overlap_activities) <- "Nodes" 

for (patient in names(cosmos_inputs)){
  # insert paths
  patient_file <- paste("d", paste(max_depth, patient, sep = ""), sep = "")
  ATT_path <- paste(data_path, paste(patient_file, "_ATT_full.csv", sep = ""), sep = "")
  ATT <- read_csv(ATT_path)
  # print(head(ATT[,c(1,7)]))
  CLL_overlap_activities[patient] <- ATT$Activity[match(CLL_overlap_activities$Nodes, ATT$Nodes)]
  print(head(CLL_overlap_activities))
}

CLL_overlap_activities[,2:10] <- round(CLL_overlap_activities[,2:10], 2)
CLL_overlap_activities$sum_CLL <- rowSums(CLL_overlap_activities[,2:5])
CLL_overlap_activities$sum_HD <- rowSums(CLL_overlap_activities[,6:10], na.rm = TRUE)

CLL_overlap <- CLL_overlap_activities[,c(1:5)]
CLL_overlap[,2:5] <- round(CLL_overlap[,2:5], 2)
CLL_overlap$sum_CLL <- rowSums(CLL_overlap[,2:5])


HD_overlap <- CLL_overlap_activities[,c(1,6:10)] # overlap between nodes that are all in CLL (not necessarily in HD)
HD_overlap[,2:6] <- round(HD_overlap[,2:6], 2)
HD_overlap$sum_HD <- rowSums(HD_overlap[,2:6], na.rm = T)

```


```{r}
load(T0_input_path)
load(T48_input_path)

max_depth <- 2
# T48_cosmos_inputs <- day2_cosmos_inputs # Laptop ONLY
cosmos_inputs <- T0_cosmos_inputs # edit these as please you
stim_point <- "T0"

# path for most data files in this project
data_path <- paste("../results/processed_results/d", paste(max_depth, paste("/", paste(stim_point, "/", sep = ""), sep = ""), sep = ""), sep = "")
# file for either CLL or HD overlap nodes
overlap_path <- paste(data_path, "HD_overlap_nodes.txt", sep = "")

# Edit below to what you want to preprocess
HD_overlap_activities <- as.data.frame(read_delim(overlap_path, delim = "/n", col_names = FALSE))
colnames(HD_overlap_activities) <- "Nodes" 

for (patient in names(cosmos_inputs)){
  # insert paths
  patient_file <- paste("d", paste(max_depth, patient, sep = ""), sep = "")
  ATT_path <- paste(data_path, paste(patient_file, "_ATT_full.csv", sep = ""), sep = "")
  ATT <- read_csv(ATT_path)
  # print(head(ATT[,c(1,7)]))
  HD_overlap_activities[patient] <- ATT$Activity[match(HD_overlap_activities$Nodes, ATT$Nodes)]
  print(head(HD_overlap_activities))
}

HD_overlap_activities[,2:10] <- round(HD_overlap_activities[,2:10], 2)
HD_overlap_activities$sum_CLL <- rowSums(HD_overlap_activities[,2:5], na.rm = TRUE)
HD_overlap_activities$sum_HD <- rowSums(HD_overlap_activities[,6:10], na.rm = TRUE)

CLL_overlap <- HD_overlap_activities[,c(1:5)]
CLL_overlap[,2:5] <- round(CLL_overlap[,2:5], 2)
CLL_overlap$sum_CLL <- rowSums(CLL_overlap[,2:5], na.rm = TRUE)


HD_overlap <- HD_overlap_activities[,c(1,6:10)]
HD_overlap[,2:6] <- round(HD_overlap[,2:6], 2)
HD_overlap$sum_HD <- rowSums(HD_overlap[,2:6], na.rm = T)
```

```{r}
all_overlap_activities <- intersect(HD_overlap_activities, CLL_overlap_activities)
all_overlap_activities_significant <- all_overlap_activities |>
  filter(all_overlap_activities$sum_CLL-all_overlap_activities$sum_HD > 2 |
           all_overlap_activities$sum_HD-all_overlap_activities$sum_CLL > 2 | 
           all_overlap_activities$sum_CLL-all_overlap_activities$sum_HD < -2 | 
           all_overlap_activities$sum_HD-all_overlap_activities$sum_CLL < -2 )
write_csv(as.data.frame(all_overlap_activities_significant$Nodes), file = paste(data_path, "significant_nodes_list.csv", sep = ""))

```

